---
title: "Lab 05: harvesting research data"
author: "Abby Komiske"
date: 2024-02-28
date-modified: today
format: 
  html:
    toc: true
---

In substitution of the lab goals, my assessment of lab 5 is below. 

## Assessment 

In lab 5, we went over harvesting data for text analysis, which pertained to identifying data sources such as CORPUS, acquiring data with database access like API, and documenting data with research scaffolding. We learned about the criteria for ‘good’ data, which includes quality, availability, accessibility (with usage rights), and data formatting. These goals for data harvesting with R are important for empirical research that is reproducible with the data origin file. In the lab, we described the data and began to go over the data collection process when we had to stop because we realized that the packages would not run on those with Macs, myself included. However, in reviewing the other steps that we would have taken in the lab, including ensuring it was reproducible and displaying the data origin file as a table, I still understand the major takeaways of the lab. 

Clearly, the major challenge of the lab was the coding itself. That proved frustrating for everyone in the class, but I think that we all did a good job of taking it in as we went. Obviously we would have all preferred for that not to happen, but that's a part of learning and coding, but especially of life! I am happy we continued on and adjusted as needed so that we could keep the big picture of the class in mind. I think this adjustment actually helped me more than if we continued the way we had been.  
